name: BlockAI
version: '1.0-SNAPSHOT'
main: io.romainmiras.blockai.Main
api-version: '1.21'
description: A plugin that adds AI to Minecraft
authors:
  - Romain Miras
contributors:
  - Romain Miras
  - Mathias Foucher
website: https://github.com/RomainMIRAS/BlockAI
load: POSTWORLD
default-permission: true
bootstrapper : io.romainmiras.blockai.Bootstrapper